create table purchase_event_types (
    code varchar(64) primary key,
    description varchar(255) null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    constraint chk_purchase_event_types_code_not_blank check (btrim(code) <> ''),
    constraint chk_purchase_event_types_description_not_blank check (
        description is null or btrim(description) <> ''
    )
);

create index idx_purchase_event_types_is_active
    on purchase_event_types (is_active, code);

create table subscription_period_types (
    code varchar(32) primary key,
    description varchar(255) null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    constraint chk_subscription_period_types_code_not_blank check (btrim(code) <> ''),
    constraint chk_subscription_period_types_description_not_blank check (
        description is null or btrim(description) <> ''
    )
);

create index idx_subscription_period_types_is_active
    on subscription_period_types (is_active, code);

create table purchase_stores (
    code varchar(32) primary key,
    description varchar(255) null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    constraint chk_purchase_stores_code_not_blank check (btrim(code) <> ''),
    constraint chk_purchase_stores_description_not_blank check (
        description is null or btrim(description) <> ''
    )
);

create index idx_purchase_stores_is_active
    on purchase_stores (is_active, code);

create table purchase_environments (
    code varchar(32) primary key,
    description varchar(255) null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    constraint chk_purchase_environments_code_not_blank check (btrim(code) <> ''),
    constraint chk_purchase_environments_description_not_blank check (
        description is null or btrim(description) <> ''
    )
);

create index idx_purchase_environments_is_active
    on purchase_environments (is_active, code);

create table purchase_reason_codes (
    reason_type varchar(32) not null,
    code varchar(64) not null,
    description varchar(255) null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    primary key (reason_type, code),
    constraint chk_purchase_reason_codes_reason_type check (
        reason_type in ('CANCEL_REASON', 'EXPIRATION_REASON')
    ),
    constraint chk_purchase_reason_codes_code_not_blank check (btrim(code) <> ''),
    constraint chk_purchase_reason_codes_description_not_blank check (
        description is null or btrim(description) <> ''
    )
);

create index idx_purchase_reason_codes_is_active
    on purchase_reason_codes (reason_type, is_active, code);

create table subscription_products (
    id bigint generated by default as identity primary key,
    store_code varchar(32) not null references purchase_stores (code),
    product_id varchar(191) not null,
    product_type varchar(32) not null,
    billing_period_unit varchar(16) not null,
    billing_period_count integer not null,
    entitlement_ids jsonb not null default '[]'::jsonb,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_subscription_products_store_product unique (store_code, product_id),
    constraint chk_subscription_products_product_id_not_blank check (
        btrim(product_id) <> ''
    ),
    constraint chk_subscription_products_product_type check (
        product_type in ('SUBSCRIPTION', 'NON_RENEWING')
    ),
    constraint chk_subscription_products_billing_period_unit check (
        billing_period_unit in ('DAY', 'WEEK', 'MONTH', 'YEAR')
    ),
    constraint chk_subscription_products_billing_period_count_positive check (
        billing_period_count > 0
    ),
    constraint chk_subscription_products_entitlement_ids_shape check (
        jsonb_typeof(entitlement_ids) in ('array', 'object')
    )
);

create index idx_subscription_products_active
    on subscription_products (is_active, store_code, product_id);

create table purchase_events (
    id bigint generated by default as identity primary key,
    app_user_id bigint null references app_users (id) on delete set null,
    source_app_user_id varchar(191) null,
    original_app_user_id varchar(191) null,
    alias_app_user_ids jsonb not null default '[]'::jsonb,
    occurred_at timestamptz not null,
    ingested_at timestamptz not null default now(),
    source varchar(32) not null,
    event_type_code varchar(64) not null references purchase_event_types (code),
    product_id varchar(191) null,
    subscription_product_id bigint null references subscription_products (id) on delete set null,
    entitlement_id varchar(191) null,
    entitlement_ids jsonb not null default '[]'::jsonb,
    store_code varchar(32) null references purchase_stores (code),
    currency_code varchar(3) null,
    price_usd numeric(12, 4) null,
    price_in_purchased_currency numeric(12, 4) null,
    price_micros bigint null,
    is_trial boolean null,
    revenuecat_event_id varchar(191) null,
    raw_payload jsonb not null,
    event_timestamp_at timestamptz null,
    expiration_at timestamptz null,
    grace_period_expiration_at timestamptz null,
    auto_resume_at timestamptz null,
    period_type_code varchar(32) null references subscription_period_types (code),
    environment_code varchar(32) null references purchase_environments (code),
    is_trial_conversion boolean null,
    cancel_reason_code varchar(64) null,
    expiration_reason_code varchar(64) null,
    transaction_id varchar(191) null,
    original_transaction_id varchar(191) null,
    renewal_number integer null,
    offer_code varchar(191) null,
    country_code varchar(2) null,
    presented_offering_id varchar(191) null,
    new_product_id varchar(191) null,
    tax_percentage numeric(6, 5) null,
    commission_percentage numeric(6, 5) null,
    net_revenue_micros bigint null,
    constraint chk_purchase_events_source check (
        source in ('REVENUECAT_WEBHOOK', 'CLIENT')
    ),
    constraint chk_purchase_events_source_app_user_id_not_blank check (
        source_app_user_id is null or btrim(source_app_user_id) <> ''
    ),
    constraint chk_purchase_events_original_app_user_id_not_blank check (
        original_app_user_id is null or btrim(original_app_user_id) <> ''
    ),
    constraint chk_purchase_events_alias_app_user_ids_shape check (
        jsonb_typeof(alias_app_user_ids) = 'array'
    ),
    constraint chk_purchase_events_product_id_not_blank check (
        product_id is null or btrim(product_id) <> ''
    ),
    constraint chk_purchase_events_entitlement_id_not_blank check (
        entitlement_id is null or btrim(entitlement_id) <> ''
    ),
    constraint chk_purchase_events_entitlement_ids_shape check (
        jsonb_typeof(entitlement_ids) = 'array'
    ),
    constraint chk_purchase_events_currency_code_format check (
        currency_code is null or currency_code ~ '^[A-Z]{3}$'
    ),
    constraint chk_purchase_events_revenuecat_event_id_not_blank check (
        revenuecat_event_id is null or btrim(revenuecat_event_id) <> ''
    ),
    constraint chk_purchase_events_raw_payload_shape check (
        jsonb_typeof(raw_payload) = 'object'
    ),
    constraint chk_purchase_events_cancel_reason_code_not_blank check (
        cancel_reason_code is null or btrim(cancel_reason_code) <> ''
    ),
    constraint chk_purchase_events_expiration_reason_code_not_blank check (
        expiration_reason_code is null or btrim(expiration_reason_code) <> ''
    ),
    constraint chk_purchase_events_transaction_id_not_blank check (
        transaction_id is null or btrim(transaction_id) <> ''
    ),
    constraint chk_purchase_events_original_transaction_id_not_blank check (
        original_transaction_id is null or btrim(original_transaction_id) <> ''
    ),
    constraint chk_purchase_events_renewal_number_positive check (
        renewal_number is null or renewal_number > 0
    ),
    constraint chk_purchase_events_offer_code_not_blank check (
        offer_code is null or btrim(offer_code) <> ''
    ),
    constraint chk_purchase_events_country_code_format check (
        country_code is null or country_code ~ '^[A-Z]{2}$'
    ),
    constraint chk_purchase_events_presented_offering_id_not_blank check (
        presented_offering_id is null or btrim(presented_offering_id) <> ''
    ),
    constraint chk_purchase_events_new_product_id_not_blank check (
        new_product_id is null or btrim(new_product_id) <> ''
    ),
    constraint chk_purchase_events_tax_percentage_range check (
        tax_percentage is null or (tax_percentage >= 0 and tax_percentage <= 1)
    ),
    constraint chk_purchase_events_commission_percentage_range check (
        commission_percentage is null or (commission_percentage >= 0 and commission_percentage <= 1)
    ),
    constraint chk_purchase_events_webhook_requires_revenuecat_event_id check (
        source <> 'REVENUECAT_WEBHOOK' or revenuecat_event_id is not null
    ),
    constraint chk_purchase_events_known_product_requires_identifiers check (
        subscription_product_id is null or (store_code is not null and product_id is not null)
    ),
    constraint chk_purchase_events_cancel_reason_type check (
        cancel_reason_code is null or event_type_code = 'CANCELLATION'
    ),
    constraint chk_purchase_events_expiration_reason_type check (
        expiration_reason_code is null or event_type_code = 'EXPIRATION'
    )
);

create unique index uk_purchase_events_revenuecat_event_id
    on purchase_events (revenuecat_event_id)
    where revenuecat_event_id is not null;
create index idx_purchase_events_app_user_occurred_at
    on purchase_events (app_user_id, occurred_at desc)
    where app_user_id is not null;
create index idx_purchase_events_event_type_occurred_at
    on purchase_events (event_type_code, occurred_at desc);
create index idx_purchase_events_store_product_occurred_at
    on purchase_events (store_code, product_id, occurred_at desc)
    where store_code is not null and product_id is not null;
create index idx_purchase_events_transaction_id
    on purchase_events (transaction_id)
    where transaction_id is not null;

create table purchase_context_snapshots (
    id bigint generated by default as identity primary key,
    purchase_event_id bigint not null references purchase_events (id) on delete cascade,
    app_user_id bigint not null references app_users (id),
    profile_id bigint null references user_profiles (id) on delete set null,
    attribution_window_seconds integer not null default 86400,
    attributed_app_event_id uuid null references app_events (event_id) on delete set null,
    attributed_content_id bigint null references contents (id) on delete set null,
    profile_snapshot jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint uk_purchase_context_snapshots_purchase_event unique (purchase_event_id),
    constraint chk_purchase_context_snapshots_window_positive check (
        attribution_window_seconds > 0
    ),
    constraint chk_purchase_context_snapshots_profile_snapshot_shape check (
        jsonb_typeof(profile_snapshot) = 'object'
    )
);

create index idx_purchase_context_snapshots_app_user_created_at
    on purchase_context_snapshots (app_user_id, created_at desc);
create index idx_purchase_context_snapshots_profile_id
    on purchase_context_snapshots (profile_id)
    where profile_id is not null;
create index idx_purchase_context_snapshots_attributed_content_id
    on purchase_context_snapshots (attributed_content_id)
    where attributed_content_id is not null;

insert into purchase_event_types (code, description) values
    ('TEST', 'Dashboard-issued test webhook'),
    ('INITIAL_PURCHASE', 'New subscription purchased'),
    ('RENEWAL', 'Existing subscription renewed'),
    ('CANCELLATION', 'Subscription or non-renewing purchase cancelled or refunded'),
    ('UNCANCELLATION', 'Cancelled subscription re-enabled before expiration'),
    ('NON_RENEWING_PURCHASE', 'Non-renewing purchase completed'),
    ('SUBSCRIPTION_PAUSED', 'Subscription scheduled to pause at period end'),
    ('EXPIRATION', 'Subscription expired and access should end'),
    ('BILLING_ISSUE', 'Store could not successfully charge the subscriber'),
    ('PRODUCT_CHANGE', 'Subscriber changed subscription product'),
    ('TRANSFER', 'Transactions and entitlements transferred between app user IDs'),
    ('SUBSCRIPTION_EXTENDED', 'Subscription expiration date extended'),
    ('TEMPORARY_ENTITLEMENT_GRANT', 'Temporary entitlement granted while store validation is unavailable'),
    ('REFUND_REVERSED', 'Refund reversal received'),
    ('INVOICE_ISSUANCE', 'Invoice issued for a web billing purchase'),
    ('VIRTUAL_CURRENCY_TRANSACTION', 'Virtual currency adjustment transaction'),
    ('EXPERIMENT_ENROLLMENT', 'Experiment enrollment webhook');

insert into subscription_period_types (code, description) values
    ('TRIAL', 'Free trial period'),
    ('INTRO', 'Introductory pricing period'),
    ('NORMAL', 'Standard subscription billing period'),
    ('PROMOTIONAL', 'Promotional entitlement period'),
    ('PREPAID', 'Prepaid Play Store billing period');

insert into purchase_stores (code, description) values
    ('AMAZON', 'Amazon Appstore'),
    ('APP_STORE', 'Apple App Store'),
    ('MAC_APP_STORE', 'Apple Mac App Store'),
    ('PADDLE', 'Paddle billing'),
    ('PLAY_STORE', 'Google Play Store'),
    ('PROMOTIONAL', 'RevenueCat promotional entitlement'),
    ('RC_BILLING', 'RevenueCat web billing'),
    ('ROKU', 'Roku billing'),
    ('STRIPE', 'Stripe billing'),
    ('TEST_STORE', 'RevenueCat test store');

insert into purchase_environments (code, description) values
    ('SANDBOX', 'Sandbox or test environment'),
    ('PRODUCTION', 'Production environment');

insert into purchase_reason_codes (reason_type, code, description) values
    ('CANCEL_REASON', 'UNSUBSCRIBE', 'Subscriber voluntarily cancelled'),
    ('CANCEL_REASON', 'BILLING_ERROR', 'Store billing error detected'),
    ('CANCEL_REASON', 'DEVELOPER_INITIATED', 'Cancellation initiated by developer'),
    ('CANCEL_REASON', 'PRICE_INCREASE', 'Subscriber rejected price increase'),
    ('CANCEL_REASON', 'CUSTOMER_SUPPORT', 'Refund or cancellation initiated by customer support'),
    ('CANCEL_REASON', 'UNKNOWN', 'Store did not provide a cancellation reason'),
    ('EXPIRATION_REASON', 'UNSUBSCRIBE', 'Subscription expired after voluntary cancellation'),
    ('EXPIRATION_REASON', 'BILLING_ERROR', 'Subscription expired after unresolved billing issue'),
    ('EXPIRATION_REASON', 'DEVELOPER_INITIATED', 'Subscription expired after developer cancellation'),
    ('EXPIRATION_REASON', 'PRICE_INCREASE', 'Subscription expired after rejected price increase'),
    ('EXPIRATION_REASON', 'CUSTOMER_SUPPORT', 'Subscription expired after customer support refund'),
    ('EXPIRATION_REASON', 'UNKNOWN', 'Store did not provide an expiration reason'),
    ('EXPIRATION_REASON', 'SUBSCRIPTION_PAUSED', 'Subscription expired because it was paused');
