create table asset_processing (
    id bigint generated by default as identity primary key,
    content_id bigint not null,
    language_code varchar(8) not null,
    status varchar(20) not null default 'PENDING',
    attempt_count integer not null default 0,
    next_attempt_at timestamptz not null default now(),
    lease_expires_at timestamptz null,
    started_at timestamptz null,
    completed_at timestamptz null,
    failed_at timestamptz null,
    last_error_code varchar(100) null,
    last_error_message text null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_asset_processing_content_language unique (content_id, language_code),
    constraint fk_asset_processing_content_localization
        foreign key (content_id, language_code)
        references content_localizations (content_id, language_code)
        on delete cascade,
    constraint chk_asset_processing_status check (
        status in ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')
    ),
    constraint chk_asset_processing_attempt_count_non_negative check (attempt_count >= 0),
    constraint chk_asset_processing_error_code_not_blank check (
        last_error_code is null or btrim(last_error_code) <> ''
    ),
    constraint chk_asset_processing_error_message_not_blank check (
        last_error_message is null or btrim(last_error_message) <> ''
    ),
    constraint chk_asset_processing_processing_window check (
        (
            status = 'PENDING'
            and lease_expires_at is null
            and completed_at is null
            and failed_at is null
        )
        or
        (
            status = 'PROCESSING'
            and started_at is not null
            and lease_expires_at is not null
            and completed_at is null
            and failed_at is null
        )
        or
        (
            status = 'COMPLETED'
            and started_at is not null
            and lease_expires_at is null
            and completed_at is not null
            and failed_at is null
        )
        or
        (
            status = 'FAILED'
            and started_at is not null
            and lease_expires_at is null
            and completed_at is null
            and failed_at is not null
        )
    )
);

create index idx_asset_processing_status_next_attempt
    on asset_processing (status, next_attempt_at);
create index idx_asset_processing_processing_lease
    on asset_processing (lease_expires_at)
    where status = 'PROCESSING';
create index idx_asset_processing_content_id
    on asset_processing (content_id);
