create table languages (
    id bigint generated by default as identity primary key,
    code varchar(8) not null,
    display_name varchar(100) not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_languages_code unique (code),
    constraint chk_languages_code_not_blank check (btrim(code) <> ''),
    constraint chk_languages_display_name_not_blank check (btrim(display_name) <> '')
);
