create table story_narrations (
    id bigint generated by default as identity primary key,
    content_localization_id bigint not null,
    audio_media_id bigint not null references media_assets (id),
    duration_minutes integer not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uk_story_narrations_localization unique (content_localization_id),
    constraint fk_story_narrations_localization foreign key (content_localization_id)
        references content_localizations (id) on delete cascade,
    constraint chk_story_narrations_audio_media_id check (audio_media_id > 0),
    constraint chk_story_narrations_duration_minutes check (duration_minutes >= 0)
);

alter table asset_processing
    add column processing_kind varchar(30) not null default 'DELIVERY';

alter table asset_processing
    add constraint chk_asset_processing_processing_kind
        check (processing_kind in ('DELIVERY', 'STORY_NARRATION'));

drop index if exists uk_asset_processing_localization_target;
drop index if exists uk_asset_processing_content_target;

create unique index uk_asset_processing_localization_target
    on asset_processing (content_id, language_code, processing_kind)
    where target_scope = 'LOCALIZATION';

create unique index uk_asset_processing_content_target
    on asset_processing (content_id, processing_kind)
    where target_scope = 'CONTENT';

create or replace function ensure_story_narration_story_localization() returns trigger
language plpgsql
as $$
begin
    if not exists (
        select 1
        from content_localizations localization
        join contents content on content.id = localization.content_id
        where localization.id = new.content_localization_id
          and content.type = 'STORY'
    ) then
        raise exception 'Story narration requires a STORY localization' using errcode = '23503';
    end if;
    return new;
end;
$$;

create trigger trg_story_narrations_ensure_story_localization
    before insert or update of content_localization_id on story_narrations
    for each row execute function ensure_story_narration_story_localization();
