DO $$
DECLARE
    invalid_content_ids text;
    conflicting_content_ids text;
    invalid_musician_assignment_ids text;
    missing_audio_ids text;
BEGIN
    SELECT string_agg(content_id::text, ', ' ORDER BY content_id)
      INTO invalid_content_ids
      FROM (
            SELECT localization.content_id
              FROM content_localizations localization
              JOIN contents content ON content.id = localization.content_id
             WHERE content.type = 'LULLABY'
               AND (
                    localization.description IS NOT NULL
                    OR localization.body_text IS NOT NULL
                    OR localization.cover_media_id IS NOT NULL
               )
             GROUP BY localization.content_id
      ) invalid;

    IF invalid_content_ids IS NOT NULL THEN
        RAISE EXCEPTION
            'V25 blocked: LULLABY localizations [%] contain fields other than title and publication state',
            invalid_content_ids;
    END IF;

    SELECT string_agg(content_id::text, ', ' ORDER BY content_id)
      INTO conflicting_content_ids
      FROM (
            SELECT localization.content_id
              FROM content_localizations localization
              JOIN contents content ON content.id = localization.content_id
             WHERE content.type = 'LULLABY'
             GROUP BY localization.content_id
            HAVING bool_or((localization.audio_media_id IS NULL)
                           <> (localization.duration_minutes IS NULL))
                OR count(DISTINCT localization.audio_media_id::text
                         || ':' || localization.duration_minutes::text) > 1
      ) conflicting;

    IF conflicting_content_ids IS NOT NULL THEN
        RAISE EXCEPTION
            'V25 blocked: LULLABY localizations [%] contain missing or conflicting audio/duration values',
            conflicting_content_ids;
    END IF;

    SELECT string_agg(assignment.id::text, ', ' ORDER BY assignment.id)
      INTO invalid_musician_assignment_ids
      FROM content_contributors assignment
      JOIN contents content ON content.id = assignment.content_id
     WHERE content.type = 'LULLABY'
       AND assignment.role = 'MUSICIAN'
       AND assignment.language_code IS NOT NULL;

    IF invalid_musician_assignment_ids IS NOT NULL THEN
        RAISE EXCEPTION
            'V25 blocked: LULLABY MUSICIAN assignments [%] are language-scoped; make them global before migrating',
            invalid_musician_assignment_ids;
    END IF;

    SELECT string_agg(localization.audio_media_id::text, ', ' ORDER BY localization.audio_media_id)
      INTO missing_audio_ids
      FROM content_localizations localization
      JOIN contents content ON content.id = localization.content_id
     WHERE content.type = 'LULLABY'
       AND localization.audio_media_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1 FROM media_assets asset WHERE asset.id = localization.audio_media_id
       );

    IF missing_audio_ids IS NOT NULL THEN
        RAISE EXCEPTION
            'V25 blocked: LULLABY audio assets [%] do not exist in media_assets',
            missing_audio_ids;
    END IF;

    SELECT string_agg(localization.audio_media_id::text, ', ' ORDER BY localization.audio_media_id)
      INTO missing_audio_ids
      FROM content_localizations localization
      JOIN contents content ON content.id = localization.content_id
      JOIN media_assets asset ON asset.id = localization.audio_media_id
     WHERE content.type = 'LULLABY'
       AND localization.audio_media_id IS NOT NULL
       AND asset.media_type <> 'AUDIO';

    IF missing_audio_ids IS NOT NULL THEN
        RAISE EXCEPTION
            'V25 blocked: LULLABY audio assets [%] are not AUDIO media assets',
            missing_audio_ids;
    END IF;
END $$;

CREATE TABLE lullaby_playbacks (
    id bigint generated by default as identity primary key,
    content_id bigint not null unique references contents (id) on delete cascade,
    audio_media_id bigint not null references media_assets (id),
    duration_minutes integer not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_lullaby_playbacks_audio_media_id_positive check (audio_media_id > 0),
    constraint chk_lullaby_playbacks_duration_minutes_non_negative check (duration_minutes >= 0)
);

CREATE INDEX idx_lullaby_playbacks_audio_media_id
    ON lullaby_playbacks (audio_media_id);

INSERT INTO lullaby_playbacks (content_id, audio_media_id, duration_minutes)
SELECT localization.content_id,
       max(localization.audio_media_id),
       max(localization.duration_minutes)
  FROM content_localizations localization
  JOIN contents content ON content.id = localization.content_id
 WHERE content.type = 'LULLABY'
   AND localization.audio_media_id IS NOT NULL
   AND localization.duration_minutes IS NOT NULL
 GROUP BY localization.content_id;

DO $$
DECLARE
    stale_processing_ids text;
BEGIN
    SELECT string_agg(processing.id::text, ', ' ORDER BY processing.id)
      INTO stale_processing_ids
      FROM asset_processing processing
      JOIN lullaby_playbacks playback ON playback.content_id = processing.content_id
      JOIN contents content ON content.id = processing.content_id
     WHERE processing.target_scope = 'CONTENT'
       AND processing.processing_kind = 'DELIVERY'
       AND content.type = 'LULLABY'
       AND (
            processing.content_type IS DISTINCT FROM 'LULLABY'
            OR processing.external_key IS DISTINCT FROM content.external_key
            OR processing.cover_source_asset_id IS DISTINCT FROM content.listening_cover_media_id
            OR processing.audio_source_asset_id IS DISTINCT FROM playback.audio_media_id
       );

    IF stale_processing_ids IS NOT NULL THEN
        RAISE EXCEPTION
            'V25 blocked: existing LULLABY CONTENT processing rows [%] do not match backfilled playback',
            stale_processing_ids;
    END IF;
END $$;

DELETE FROM asset_processing processing
USING contents content
 WHERE processing.target_scope = 'LOCALIZATION'
   AND processing.processing_kind = 'DELIVERY'
   AND processing.content_id = content.id
   AND content.type = 'LULLABY';

UPDATE content_localizations localization
   SET audio_media_id = NULL,
       duration_minutes = NULL,
       processing_status = 'PENDING',
       updated_at = now()
 WHERE EXISTS (
           SELECT 1
             FROM contents content
            WHERE content.id = localization.content_id
              AND content.type = 'LULLABY'
       );

INSERT INTO asset_processing (
    content_id,
    language_code,
    status,
    content_type,
    external_key,
    cover_source_asset_id,
    audio_source_asset_id,
    page_count,
    target_scope
)
SELECT content.id,
       NULL,
       'PENDING',
       'LULLABY',
       content.external_key,
       content.listening_cover_media_id,
       playback.audio_media_id,
       NULL,
       'CONTENT'
  FROM lullaby_playbacks playback
  JOIN contents content ON content.id = playback.content_id
 WHERE NOT EXISTS (
           SELECT 1
             FROM asset_processing existing
            WHERE existing.target_scope = 'CONTENT'
              AND existing.content_id = content.id
       );

CREATE OR REPLACE FUNCTION ensure_lullaby_playback_content_type() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM media_assets
         WHERE id = NEW.audio_media_id
           AND media_type = 'AUDIO'
    ) THEN
        RAISE EXCEPTION 'Lullaby playback audio must reference an AUDIO asset: %', NEW.audio_media_id
            USING errcode = '23514';
    END IF;
    IF NOT EXISTS (
        SELECT 1
          FROM contents
         WHERE id = NEW.content_id
           AND type = 'LULLABY'
    ) THEN
        RAISE EXCEPTION 'Lullaby playback requires LULLABY content: %', NEW.content_id
            USING errcode = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_lullaby_playbacks_ensure_content_type
    BEFORE INSERT OR UPDATE OF content_id, audio_media_id ON lullaby_playbacks
    FOR EACH ROW
EXECUTE FUNCTION ensure_lullaby_playback_content_type();

CREATE OR REPLACE FUNCTION ensure_lullaby_content_type_transition() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.type <> 'LULLABY' AND EXISTS (
        SELECT 1 FROM lullaby_playbacks WHERE content_id = NEW.id
    ) THEN
        RAISE EXCEPTION 'Content % cannot leave LULLABY while playback exists', NEW.id
            USING errcode = '23514';
    END IF;

    IF NEW.type = 'LULLABY' THEN
        IF EXISTS (
            SELECT 1
              FROM content_localizations
             WHERE content_id = NEW.id
               AND (description IS NOT NULL OR body_text IS NOT NULL
                    OR cover_media_id IS NOT NULL OR audio_media_id IS NOT NULL
                    OR duration_minutes IS NOT NULL)
        ) THEN
            RAISE EXCEPTION 'Content % cannot become LULLABY with non-title localization fields', NEW.id
                USING errcode = '23514';
        END IF;
        IF EXISTS (
            SELECT 1
              FROM content_contributors
             WHERE content_id = NEW.id
               AND role = 'MUSICIAN'
               AND language_code IS NOT NULL
        ) THEN
            RAISE EXCEPTION 'Content % cannot become LULLABY with localized MUSICIAN assignments', NEW.id
                USING errcode = '23514';
        END IF;
        IF EXISTS (
            SELECT 1
              FROM content_localizations
             WHERE content_id = NEW.id
               AND processing_status <> 'PENDING'
        ) THEN
            RAISE EXCEPTION 'Content % cannot become LULLABY with non-pending localization processing', NEW.id
                USING errcode = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_contents_ensure_lullaby_type_transition
    BEFORE UPDATE OF type ON contents
    FOR EACH ROW
EXECUTE FUNCTION ensure_lullaby_content_type_transition();

CREATE OR REPLACE FUNCTION ensure_lullaby_localization_title_only() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM contents
         WHERE id = NEW.content_id
           AND type = 'LULLABY'
    ) AND (
        NEW.description IS NOT NULL
        OR NEW.body_text IS NOT NULL
        OR NEW.cover_media_id IS NOT NULL
        OR NEW.audio_media_id IS NOT NULL
        OR NEW.duration_minutes IS NOT NULL
    ) THEN
        RAISE EXCEPTION
            'LULLABY localizations support only title and publication state: content %, language %',
            NEW.content_id, NEW.language_code
            USING errcode = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_lullaby_localizations_title_only
    BEFORE INSERT OR UPDATE OF content_id, description, body_text, cover_media_id,
        audio_media_id, duration_minutes ON content_localizations
    FOR EACH ROW
EXECUTE FUNCTION ensure_lullaby_localization_title_only();

CREATE OR REPLACE FUNCTION ensure_lullaby_localization_processing_pending() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.processing_status <> 'PENDING'
       AND EXISTS (
           SELECT 1
             FROM contents
            WHERE id = NEW.content_id
              AND type = 'LULLABY'
       ) THEN
        RAISE EXCEPTION
            'LULLABY processing status is owned by shared playback: content %, language %',
            NEW.content_id, NEW.language_code
            USING errcode = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_lullaby_localizations_processing_pending
    BEFORE INSERT OR UPDATE OF content_id, processing_status ON content_localizations
    FOR EACH ROW
EXECUTE FUNCTION ensure_lullaby_localization_processing_pending();

CREATE OR REPLACE FUNCTION ensure_lullaby_musician_global() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.role = 'MUSICIAN'
       AND NEW.language_code IS NOT NULL
       AND EXISTS (
           SELECT 1
             FROM contents
            WHERE id = NEW.content_id
              AND type = 'LULLABY'
       ) THEN
        RAISE EXCEPTION
            'LULLABY MUSICIAN assignments must be global: content %, language %',
            NEW.content_id, NEW.language_code
            USING errcode = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_lullaby_musician_global
    BEFORE INSERT OR UPDATE OF content_id, role, language_code ON content_contributors
    FOR EACH ROW
EXECUTE FUNCTION ensure_lullaby_musician_global();
