CREATE TABLE instrument_catalogs (
    id bigint generated by default as identity primary key,
    code varchar(64) not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_instrument_catalogs_code unique (code),
    constraint chk_instrument_catalogs_code_not_blank check (btrim(code) <> ''),
    constraint chk_instrument_catalogs_code_normalized check (code = upper(btrim(code)))
);

CREATE TABLE instrument_catalog_localizations (
    id bigint generated by default as identity primary key,
    instrument_catalog_id bigint not null references instrument_catalogs (id) on delete cascade,
    language_code varchar(8) not null references languages (code),
    display_name varchar(255) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_instrument_catalog_localizations_catalog_language
        unique (instrument_catalog_id, language_code),
    constraint chk_instrument_catalog_localizations_display_name_not_blank
        check (btrim(display_name) <> '')
);

CREATE INDEX idx_instrument_catalog_localizations_language
    ON instrument_catalog_localizations (language_code, instrument_catalog_id);

CREATE TABLE lullaby_instruments (
    id bigint generated by default as identity primary key,
    content_id bigint not null references contents (id) on delete cascade,
    instrument_catalog_id bigint not null references instrument_catalogs (id),
    display_order integer not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_lullaby_instruments_content_catalog
        unique (content_id, instrument_catalog_id),
    constraint uk_lullaby_instruments_content_order
        unique (content_id, display_order),
    constraint chk_lullaby_instruments_display_order_non_negative
        check (display_order >= 0)
);

CREATE INDEX idx_lullaby_instruments_content_order
    ON lullaby_instruments (content_id, display_order);
CREATE INDEX idx_lullaby_instruments_catalog
    ON lullaby_instruments (instrument_catalog_id);

INSERT INTO instrument_catalogs (code, is_active)
VALUES
    ('CELESTA', true),
    ('BELL', true),
    ('VIOLIN', true),
    ('RHODES', true),
    ('GLOCKENSPIEL', true),
    ('HARP', true),
    ('VIBRAPHONE', true),
    ('STRING_ORCHESTRA', true);

INSERT INTO instrument_catalog_localizations (instrument_catalog_id, language_code, display_name)
SELECT catalog.id, 'tr', labels.display_name
  FROM instrument_catalogs catalog
  JOIN (
      VALUES
          ('CELESTA', 'Çelesta'),
          ('BELL', 'Bell'),
          ('VIOLIN', 'Keman'),
          ('RHODES', 'Rhodes'),
          ('GLOCKENSPIEL', 'Glockenspiel'),
          ('HARP', 'Arp'),
          ('VIBRAPHONE', 'Vibrafon'),
          ('STRING_ORCHESTRA', 'Yaylı Orkestra')
  ) AS labels(code, display_name) ON labels.code = catalog.code;

CREATE OR REPLACE FUNCTION ensure_lullaby_instrument_content_type() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM contents
         WHERE id = NEW.content_id
           AND type = 'LULLABY'
    ) THEN
        RAISE EXCEPTION 'Lullaby instrument requires LULLABY content: %', NEW.content_id
            USING errcode = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_lullaby_instruments_ensure_content_type
    BEFORE INSERT OR UPDATE OF content_id ON lullaby_instruments
    FOR EACH ROW
EXECUTE FUNCTION ensure_lullaby_instrument_content_type();

CREATE OR REPLACE FUNCTION ensure_lullaby_content_instrument_type_transition() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.type <> 'LULLABY' AND EXISTS (
        SELECT 1
          FROM lullaby_instruments
         WHERE content_id = NEW.id
    ) THEN
        RAISE EXCEPTION 'Content % cannot leave LULLABY while instruments exist', NEW.id
            USING errcode = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_contents_ensure_lullaby_instrument_type_transition
    BEFORE UPDATE OF type ON contents
    FOR EACH ROW
EXECUTE FUNCTION ensure_lullaby_content_instrument_type_transition();
