create table admin_users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null,
    password_hash varchar(255) not null,
    is_active boolean not null default true,
    last_login_at timestamptz null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_admin_users_username unique (username),
    constraint chk_admin_users_username_not_blank check (btrim(username) <> ''),
    constraint chk_admin_users_password_hash_not_blank check (btrim(password_hash) <> '')
);

create table admin_roles (
    id bigint generated by default as identity primary key,
    code varchar(50) not null,
    description varchar(255) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_admin_roles_code unique (code),
    constraint chk_admin_roles_code_not_blank check (btrim(code) <> ''),
    constraint chk_admin_roles_code_format check (code ~ '^[A-Z][A-Z0-9_]*$'),
    constraint chk_admin_roles_description_not_blank check (btrim(description) <> '')
);

create table admin_user_roles (
    id bigint generated by default as identity primary key,
    admin_user_id bigint not null,
    admin_role_id bigint not null,
    assigned_at timestamptz not null default now(),
    constraint uk_admin_user_roles_assignment unique (admin_user_id, admin_role_id),
    constraint fk_admin_user_roles_admin_user
        foreign key (admin_user_id) references admin_users (id) on delete cascade,
    constraint fk_admin_user_roles_admin_role
        foreign key (admin_role_id) references admin_roles (id) on delete cascade
);

create index idx_admin_user_roles_admin_user_id on admin_user_roles (admin_user_id);
create index idx_admin_user_roles_admin_role_id on admin_user_roles (admin_role_id);

create table admin_refresh_tokens (
    id bigint generated by default as identity primary key,
    admin_user_id bigint not null,
    refresh_token_hash varchar(128) not null,
    replaced_by_token_hash varchar(128) null,
    issued_at timestamptz not null default now(),
    expires_at timestamptz not null,
    revoked_at timestamptz null,
    user_agent varchar(512) null,
    ip_address varchar(64) null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_admin_refresh_tokens_hash unique (refresh_token_hash),
    constraint fk_admin_refresh_tokens_admin_user
        foreign key (admin_user_id) references admin_users (id) on delete cascade,
    constraint chk_admin_refresh_tokens_hash_not_blank check (btrim(refresh_token_hash) <> ''),
    constraint chk_admin_refresh_tokens_replaced_hash_not_blank
        check (replaced_by_token_hash is null or btrim(replaced_by_token_hash) <> ''),
    constraint chk_admin_refresh_tokens_expiry_after_issue check (expires_at > issued_at),
    constraint chk_admin_refresh_tokens_revoked_after_issue
        check (revoked_at is null or revoked_at >= issued_at)
);

create index idx_admin_refresh_tokens_admin_user_id on admin_refresh_tokens (admin_user_id);
create index idx_admin_refresh_tokens_admin_user_active
    on admin_refresh_tokens (admin_user_id, expires_at desc)
    where revoked_at is null;

insert into admin_roles (code, description)
values
    ('ADMIN', 'Full administrative access'),
    ('CONTENT_MANAGER', 'Can manage content and curation workflows'),
    ('VIEWER', 'Read-only CMS access');
