create table media_assets (
    id bigint generated by default as identity primary key,
    provider varchar(50) not null,
    object_path varchar(1024) not null,
    media_type varchar(20) not null,
    kind varchar(50) not null,
    mime_type varchar(255) null,
    byte_size bigint null,
    checksum_sha256 varchar(64) null,
    cached_download_url text null,
    download_url_cached_at timestamptz null,
    download_url_expires_at timestamptz null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_media_assets_provider_object_path unique (provider, object_path),
    constraint chk_media_assets_provider_not_blank check (btrim(provider) <> ''),
    constraint chk_media_assets_provider_format check (provider ~ '^[A-Z][A-Z0-9_]*$'),
    constraint chk_media_assets_object_path_not_blank check (btrim(object_path) <> ''),
    constraint chk_media_assets_media_type check (media_type in ('IMAGE', 'AUDIO', 'ARCHIVE')),
    constraint chk_media_assets_kind check (
        kind in (
            'ORIGINAL_IMAGE',
            'ORIGINAL_AUDIO',
            'THUMBNAIL_PHONE',
            'THUMBNAIL_TABLET',
            'DETAIL_PHONE',
            'DETAIL_TABLET',
            'OPTIMIZED_AUDIO',
            'CONTENT_ZIP',
            'CONTENT_ZIP_PART1',
            'CONTENT_ZIP_PART2'
        )
    ),
    constraint chk_media_assets_kind_matches_media_type check (
        (media_type = 'IMAGE' and kind in (
            'ORIGINAL_IMAGE',
            'THUMBNAIL_PHONE',
            'THUMBNAIL_TABLET',
            'DETAIL_PHONE',
            'DETAIL_TABLET'
        ))
        or
        (media_type = 'AUDIO' and kind in (
            'ORIGINAL_AUDIO',
            'OPTIMIZED_AUDIO'
        ))
        or
        (media_type = 'ARCHIVE' and kind in (
            'CONTENT_ZIP',
            'CONTENT_ZIP_PART1',
            'CONTENT_ZIP_PART2'
        ))
    ),
    constraint chk_media_assets_byte_size_non_negative check (byte_size is null or byte_size >= 0),
    constraint chk_media_assets_checksum_sha256_format check (
        checksum_sha256 is null or checksum_sha256 ~ '^[0-9a-f]{64}$'
    ),
    constraint chk_media_assets_cached_download_url_not_blank check (
        cached_download_url is null or btrim(cached_download_url) <> ''
    ),
    constraint chk_media_assets_download_url_cache_timestamps check (
        (cached_download_url is null and download_url_cached_at is null and download_url_expires_at is null)
        or
        (
            cached_download_url is not null
            and download_url_cached_at is not null
            and download_url_expires_at is not null
            and download_url_expires_at > download_url_cached_at
        )
    )
);

create index idx_media_assets_media_type_kind on media_assets (media_type, kind);
create index idx_media_assets_download_url_expires_at
    on media_assets (download_url_expires_at)
    where cached_download_url is not null;
