create table contents (
    id bigint generated by default as identity primary key,
    type varchar(20) not null,
    external_key varchar(180) not null,
    is_active boolean not null default true,
    age_range smallint null,
    page_count integer null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_contents_external_key unique (external_key),
    constraint chk_contents_type check (
        type in ('STORY', 'AUDIO_STORY', 'MEDITATION', 'LULLABY')
    ),
    constraint chk_contents_external_key_not_blank check (btrim(external_key) <> ''),
    constraint chk_contents_age_range_non_negative check (
        age_range is null or age_range >= 0
    ),
    constraint chk_contents_page_count_by_type check (
        (type = 'STORY' and page_count is not null and page_count >= 0)
        or
        (type <> 'STORY' and page_count is null)
    )
);

create index idx_contents_type_is_active on contents (type, is_active);

create table content_localizations (
    id bigint generated by default as identity primary key,
    content_id bigint not null references contents (id) on delete cascade,
    language_code varchar(8) not null references languages (code),
    title varchar(255) not null,
    description text null,
    body_text text null,
    cover_media_id bigint null,
    audio_media_id bigint null,
    duration_minutes integer null,
    status varchar(20) not null default 'DRAFT',
    processing_status varchar(20) not null default 'PENDING',
    published_at timestamptz null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_content_localizations_content_language unique (content_id, language_code),
    constraint chk_content_localizations_title_not_blank check (btrim(title) <> ''),
    constraint chk_content_localizations_description_not_blank check (
        description is null or btrim(description) <> ''
    ),
    constraint chk_content_localizations_body_text_not_blank check (
        body_text is null or btrim(body_text) <> ''
    ),
    constraint chk_content_localizations_cover_media_id_positive check (
        cover_media_id is null or cover_media_id > 0
    ),
    constraint chk_content_localizations_audio_media_id_positive check (
        audio_media_id is null or audio_media_id > 0
    ),
    constraint chk_content_localizations_duration_non_negative check (
        duration_minutes is null or duration_minutes >= 0
    ),
    constraint chk_content_localizations_status check (
        status in ('DRAFT', 'PUBLISHED', 'ARCHIVED')
    ),
    constraint chk_content_localizations_processing_status check (
        processing_status in ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')
    ),
    constraint chk_content_localizations_published_at check (
        status <> 'PUBLISHED' or published_at is not null
    )
);

create index idx_content_localizations_language_status
    on content_localizations (language_code, status, processing_status);
create index idx_content_localizations_cover_media_id
    on content_localizations (cover_media_id)
    where cover_media_id is not null;
create index idx_content_localizations_audio_media_id
    on content_localizations (audio_media_id)
    where audio_media_id is not null;

create table story_pages (
    id bigint generated by default as identity primary key,
    content_id bigint not null references contents (id) on delete cascade,
    page_number integer not null,
    illustration_media_id bigint null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_story_pages_content_page unique (content_id, page_number),
    constraint chk_story_pages_page_number_positive check (page_number > 0),
    constraint chk_story_pages_illustration_media_id_positive check (
        illustration_media_id is null or illustration_media_id > 0
    )
);

create index idx_story_pages_content_id on story_pages (content_id);
create index idx_story_pages_illustration_media_id
    on story_pages (illustration_media_id)
    where illustration_media_id is not null;

create table story_page_localizations (
    id bigint generated by default as identity primary key,
    story_page_id bigint not null references story_pages (id) on delete cascade,
    language_code varchar(8) not null references languages (code),
    body_text text null,
    audio_media_id bigint null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_story_page_localizations_page_language unique (story_page_id, language_code),
    constraint chk_story_page_localizations_body_text_not_blank check (
        body_text is null or btrim(body_text) <> ''
    ),
    constraint chk_story_page_localizations_audio_media_id_positive check (
        audio_media_id is null or audio_media_id > 0
    )
);

create index idx_story_page_localizations_story_page_id
    on story_page_localizations (story_page_id);
create index idx_story_page_localizations_audio_media_id
    on story_page_localizations (audio_media_id)
    where audio_media_id is not null;

create function ensure_story_page_content_type() returns trigger
language plpgsql
as $$
declare
    owner_content_type varchar(20);
begin
    select type
    into owner_content_type
    from contents
    where id = new.content_id;

    if owner_content_type is null then
        raise exception 'Content not found for story page: %', new.content_id
            using errcode = '23503';
    end if;

    if owner_content_type <> 'STORY' then
        raise exception 'Story pages can only belong to STORY content: %', new.content_id
            using errcode = '23514';
    end if;

    return new;
end;
$$;

create trigger trg_story_pages_ensure_story_content
    before insert or update on story_pages
    for each row
execute function ensure_story_page_content_type();

create function ensure_story_page_localization_content_language() returns trigger
language plpgsql
as $$
declare
    owner_content_id bigint;
begin
    select content_id
    into owner_content_id
    from story_pages
    where id = new.story_page_id;

    if owner_content_id is null then
        raise exception 'Story page not found for localization: %', new.story_page_id
            using errcode = '23503';
    end if;

    if not exists (
        select 1
        from content_localizations
        where content_id = owner_content_id
          and language_code = new.language_code
    ) then
        raise exception 'Content localization missing for story page localization: content %, language %',
            owner_content_id,
            new.language_code
            using errcode = '23503';
    end if;

    return new;
end;
$$;

create trigger trg_story_page_localizations_require_content_localization
    before insert or update on story_page_localizations
    for each row
execute function ensure_story_page_localization_content_language();

create function sync_story_page_count() returns trigger
language plpgsql
as $$
begin
    if tg_op in ('INSERT', 'UPDATE') then
        update contents
        set page_count = (
                select count(*)
                from story_pages
                where content_id = new.content_id
            ),
            updated_at = now()
        where id = new.content_id;
    end if;

    if tg_op in ('DELETE', 'UPDATE')
        and (tg_op <> 'UPDATE' or old.content_id <> new.content_id) then
        update contents
        set page_count = (
                select count(*)
                from story_pages
                where content_id = old.content_id
            ),
            updated_at = now()
        where id = old.content_id;
    end if;

    return null;
end;
$$;

create trigger trg_story_pages_sync_page_count
    after insert or update or delete on story_pages
    for each row
execute function sync_story_page_count();
