create table contributors (
    id bigint generated by default as identity primary key,
    display_name varchar(200) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_contributors_display_name_not_blank check (btrim(display_name) <> '')
);

create index idx_contributors_display_name on contributors (display_name);

create table content_contributors (
    id bigint generated by default as identity primary key,
    content_id bigint not null references contents (id) on delete cascade,
    contributor_id bigint not null references contributors (id),
    role varchar(20) not null,
    language_code varchar(8) null references languages (code),
    credit_name varchar(200) null,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_content_contributors_role check (
        role in ('AUTHOR', 'ILLUSTRATOR', 'NARRATOR', 'MUSICIAN')
    ),
    constraint chk_content_contributors_credit_name_not_blank check (
        credit_name is null or btrim(credit_name) <> ''
    ),
    constraint chk_content_contributors_sort_order_non_negative check (
        sort_order >= 0
    )
);

create index idx_content_contributors_content_id
    on content_contributors (content_id);
create index idx_content_contributors_contributor_id
    on content_contributors (contributor_id);
create index idx_content_contributors_content_role_language
    on content_contributors (content_id, role, language_code, sort_order);

create unique index uk_content_contributors_assignment_global
    on content_contributors (content_id, contributor_id, role)
    where language_code is null;

create unique index uk_content_contributors_assignment_localized
    on content_contributors (content_id, contributor_id, role, language_code)
    where language_code is not null;

create unique index uk_content_contributors_sort_order_global
    on content_contributors (content_id, role, sort_order)
    where language_code is null;

create unique index uk_content_contributors_sort_order_localized
    on content_contributors (content_id, role, language_code, sort_order)
    where language_code is not null;
