create table categories (
    id bigint generated by default as identity primary key,
    slug varchar(180) not null,
    type varchar(20) not null,
    is_premium boolean not null default false,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_categories_slug unique (slug),
    constraint chk_categories_slug_not_blank check (btrim(slug) <> ''),
    constraint chk_categories_type check (
        type in ('CONTENT', 'PARENT_GUIDANCE')
    )
);

create index idx_categories_type_is_active on categories (type, is_active);

create table category_localizations (
    id bigint generated by default as identity primary key,
    category_id bigint not null references categories (id) on delete cascade,
    language_code varchar(8) not null references languages (code),
    name varchar(255) not null,
    description text null,
    image_media_id bigint null,
    status varchar(20) not null default 'DRAFT',
    published_at timestamptz null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_category_localizations_category_language unique (category_id, language_code),
    constraint chk_category_localizations_name_not_blank check (btrim(name) <> ''),
    constraint chk_category_localizations_description_not_blank check (
        description is null or btrim(description) <> ''
    ),
    constraint chk_category_localizations_image_media_id_positive check (
        image_media_id is null or image_media_id > 0
    ),
    constraint chk_category_localizations_status check (
        status in ('DRAFT', 'PUBLISHED', 'ARCHIVED')
    ),
    constraint chk_category_localizations_published_at check (
        status <> 'PUBLISHED' or published_at is not null
    )
);

create index idx_category_localizations_language_status
    on category_localizations (language_code, status);
create index idx_category_localizations_image_media_id
    on category_localizations (image_media_id)
    where image_media_id is not null;

create table category_contents (
    id bigint generated by default as identity primary key,
    category_id bigint not null references categories (id) on delete cascade,
    language_code varchar(8) not null references languages (code),
    content_id bigint not null references contents (id) on delete cascade,
    display_order integer not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_category_contents_category_language_content unique (category_id, language_code, content_id),
    constraint uk_category_contents_category_language_order unique (category_id, language_code, display_order),
    constraint chk_category_contents_display_order_non_negative check (
        display_order >= 0
    )
);

create index idx_category_contents_category_language_order
    on category_contents (category_id, language_code, display_order);
create index idx_category_contents_content_id on category_contents (content_id);

create function ensure_category_content_localizations_exist() returns trigger
language plpgsql
as $$
begin
    if not exists (
        select 1
        from category_localizations
        where category_id = new.category_id
          and language_code = new.language_code
    ) then
        raise exception 'Category localization missing for category content: category %, language %',
            new.category_id,
            new.language_code
            using errcode = '23503';
    end if;

    if not exists (
        select 1
        from content_localizations
        where content_id = new.content_id
          and language_code = new.language_code
    ) then
        raise exception 'Content localization missing for category content: content %, language %',
            new.content_id,
            new.language_code
            using errcode = '23503';
    end if;

    return new;
end;
$$;

create trigger trg_category_contents_require_localizations
    before insert or update on category_contents
    for each row
execute function ensure_category_content_localizations_exist();
