create table content_free_access (
    id bigint generated by default as identity primary key,
    access_key varchar(120) not null default 'default',
    content_id bigint not null references contents (id) on delete cascade,
    language_code varchar(8) not null references languages (code),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_content_free_access_access_key_content_language unique (
        access_key,
        content_id,
        language_code
    ),
    constraint chk_content_free_access_access_key_not_blank check (
        btrim(access_key) <> ''
    )
);

create index idx_content_free_access_access_key_language
    on content_free_access (access_key, language_code, content_id);

create index idx_content_free_access_content_language
    on content_free_access (content_id, language_code, access_key);
