create table app_users (
    id bigint generated by default as identity primary key,
    firebase_uid varchar(191) not null,
    is_allow_marketing boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_app_users_firebase_uid unique (firebase_uid),
    constraint chk_app_users_firebase_uid_not_blank check (btrim(firebase_uid) <> '')
);

create table user_profiles (
    id bigint generated by default as identity primary key,
    app_user_id bigint not null references app_users (id) on delete cascade,
    display_name varchar(120) null,
    age_range varchar(40) not null default 'UNKNOWN',
    avatar_media_id bigint null,
    favorite_genres text[] not null default '{}'::text[],
    main_purposes text[] not null default '{}'::text[],
    is_primary boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_user_profiles_display_name_not_blank check (
        display_name is null or btrim(display_name) <> ''
    ),
    constraint chk_user_profiles_age_range_not_blank check (btrim(age_range) <> ''),
    constraint chk_user_profiles_avatar_media_id_positive check (
        avatar_media_id is null or avatar_media_id > 0
    )
);

create index idx_user_profiles_app_user_id on user_profiles (app_user_id);
create unique index uk_user_profiles_primary_profile
    on user_profiles (app_user_id)
    where is_primary;
create index idx_user_profiles_avatar_media_id
    on user_profiles (avatar_media_id)
    where avatar_media_id is not null;
