@startuml
title <size:24>Event</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("TellPalApplication_boundary", "TellPalApplication", $tags="") {
  Container_Boundary("TellPalApplication.TellPalApplication_boundary", "TellPalApplication", $tags="") {
    Component(TellPalApplication.TellPalApplication.Shared, "Shared", $techn="Module", $descr="", $tags="", $link="")
    Component(TellPalApplication.TellPalApplication.Content, "Content", $techn="Module", $descr="", $tags="", $link="")
    Component(TellPalApplication.TellPalApplication.User, "User", $techn="Module", $descr="", $tags="", $link="")
    Component(TellPalApplication.TellPalApplication.Event, "Event", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(TellPalApplication.TellPalApplication.User, TellPalApplication.TellPalApplication.Shared, "depends on", $techn="", $tags="", $link="")
Rel(TellPalApplication.TellPalApplication.Event, TellPalApplication.TellPalApplication.Shared, "depends on", $techn="", $tags="", $link="")
Rel(TellPalApplication.TellPalApplication.Event, TellPalApplication.TellPalApplication.Content, "uses", $techn="", $tags="", $link="")
Rel(TellPalApplication.TellPalApplication.Event, TellPalApplication.TellPalApplication.User, "uses", $techn="", $tags="", $link="")
Rel(TellPalApplication.TellPalApplication.Content, TellPalApplication.TellPalApplication.Shared, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml