import type {
  MockupCategory,
  MockupCategorySummary,
  MockupContent,
  MockupContentSummary,
  MockupStoryPage,
} from "@/features/mockups/types";

export const mockupDemoContent: MockupContent = {
  id: "demo-content",
  externalKey: "story.starlit-harbor",
  typeLabel: "STORY",
  active: true,
  ageRange: 6,
  pageCount: 4,
  summaryLabel: "Editorial workspace seed",
  note: "Primary demo record for Variant A shell validation.",
  isDemo: true,
  readinessSummary:
    "English is publish-ready, Turkish is in editorial review, and story pages are wired from the same shell.",
  primaryAction: "Open the story page editor with the current locale focus.",
  workingAgreements: [
    "Metadata stays quiet in the main lane while readiness moves into the rail.",
    "Each locale keeps its own publishing and asset narrative on the same screen.",
    "Story page handoff preserves the editor's selected language.",
  ],
  contributorAssignments: [
    {
      id: "contrib-1",
      role: "Author",
      name: "Lina Hart",
      languageCode: "en",
      creditName: "Lina Hart",
      order: 1,
      note: "Primary narrative owner for the English release.",
    },
    {
      id: "contrib-2",
      role: "Translator",
      name: "Mert Aydin",
      languageCode: "tr",
      creditName: "Mert Aydin",
      order: 2,
      note: "Keeps Turkish copy aligned with bedtime tone rules.",
    },
    {
      id: "contrib-3",
      role: "Illustration",
      name: "Sora Vale",
      languageCode: "en",
      creditName: "Sora Vale",
      order: 3,
      note: "Owns cover direction and story page illustration rhythm.",
    },
  ],
  locales: [
    {
      languageCode: "en",
      title: "Starlit Harbor",
      description: "A quiet harbor walk that slows the bedtime routine.",
      statusLabel: "Published",
      isPublished: true,
      isVisibleToMobile: true,
      isProcessingComplete: true,
      hasCover: true,
      hasAudio: true,
      note: "Primary release locale with complete cover, audio, and page readiness.",
    },
    {
      languageCode: "tr",
      title: "Yildizli Liman",
      description: "Uyku oncesi sakinlesmeyi odaga alan liman hikayesi.",
      statusLabel: "In review",
      isPublished: false,
      isVisibleToMobile: false,
      isProcessingComplete: false,
      hasCover: true,
      hasAudio: false,
      note: "Copy is staged for review while narration and processing are still pending.",
    },
  ],
};

export const mockupReferenceMeditation: MockupContentSummary = {
  id: "reference-meditation",
  externalKey: "meditation.rain-window-reset",
  typeLabel: "MEDITATION",
  active: true,
  ageRange: 8,
  pageCount: null,
  summaryLabel: "Reference item",
  note: "Used to show how the registry handles non-story records in the same shell.",
  isDemo: false,
  locales: [
    {
      languageCode: "en",
      title: "Rain Window Reset",
      description: "Breathing reset with a short ambient loop.",
      statusLabel: "Draft",
      isPublished: false,
      isVisibleToMobile: false,
      isProcessingComplete: false,
      hasCover: false,
      hasAudio: true,
      note: "Audio exists, but the release checklist is still incomplete.",
    },
  ],
};

export const mockupReferenceLullaby: MockupContentSummary = {
  id: "reference-lullaby",
  externalKey: "lullaby.moon-drift",
  typeLabel: "LULLABY",
  active: false,
  ageRange: 3,
  pageCount: null,
  summaryLabel: "Reference item",
  note: "Shows the inactive state and archive posture inside the same registry.",
  isDemo: false,
  locales: [
    {
      languageCode: "en",
      title: "Moon Drift",
      description: "Soft hum with a low-energy sleep loop.",
      statusLabel: "Archived",
      isPublished: false,
      isVisibleToMobile: false,
      isProcessingComplete: true,
      hasCover: true,
      hasAudio: true,
      note: "Archived but still preserved as a registry reference.",
    },
  ],
};

export const mockupContentRegistry: MockupContentSummary[] = [
  mockupDemoContent,
  mockupReferenceMeditation,
  mockupReferenceLullaby,
];

export const mockupDemoCategory: MockupCategory = {
  id: "demo-category",
  slug: "quiet-harbor-picks",
  typeLabel: "STORY",
  premium: false,
  active: true,
  note: "Primary demo category for Variant A category workspace.",
  isDemo: true,
  guardrails: [
    "Only published locale workspaces can drive ordering changes.",
    "The rail keeps curation prerequisites visible without crowding the main lane.",
    "Localization and curation stay on one route so editors do not lose context.",
  ],
  curationItems: [
    {
      id: "curation-1",
      contentTitle: "Starlit Harbor",
      contentType: "STORY",
      languageCode: "en",
      displayOrder: 1,
      statusLabel: "Published",
      reason: "Lead story for the English bedtime shelf.",
    },
    {
      id: "curation-2",
      contentTitle: "Lantern Train",
      contentType: "STORY",
      languageCode: "en",
      displayOrder: 2,
      statusLabel: "Published",
      reason: "Supports a calmer second-slot tempo.",
    },
    {
      id: "curation-3",
      contentTitle: "Yildizli Liman",
      contentType: "STORY",
      languageCode: "tr",
      displayOrder: 1,
      statusLabel: "Draft locale",
      reason: "Visible as a working draft even though release prerequisites are not met yet.",
    },
  ],
  locales: [
    {
      languageCode: "en",
      title: "Quiet Harbor Picks",
      description: "Featured harbor stories for a slow bedtime ramp.",
      statusLabel: "Published",
      isPublished: true,
      hasIllustration: true,
      note: "English curation is live and image-complete.",
    },
    {
      languageCode: "tr",
      title: "Sakin Liman Seckileri",
      description: "Uyku oncesi liman temasinda secilmis hikayeler.",
      statusLabel: "Draft",
      isPublished: false,
      hasIllustration: false,
      note: "Turkish is staged but still waiting on cover art and publication.",
    },
  ],
};

export const mockupReferenceCategory: MockupCategorySummary = {
  id: "reference-category",
  slug: "premium-night-sounds",
  typeLabel: "MEDITATION",
  premium: true,
  active: true,
  note: "Reference entry for premium access signaling in the registry.",
  isDemo: false,
  locales: [
    {
      languageCode: "en",
      title: "Premium Night Sounds",
      description: "Meditation and ambience for long-form wind-down sessions.",
      statusLabel: "Published",
      isPublished: true,
      hasIllustration: true,
      note: "Stable premium category with complete localization assets.",
    },
  ],
};

export const mockupArchivedCategory: MockupCategorySummary = {
  id: "archived-category",
  slug: "retired-lullabies",
  typeLabel: "LULLABY",
  premium: false,
  active: false,
  note: "Reference entry for inactive category state.",
  isDemo: false,
  locales: [
    {
      languageCode: "en",
      title: "Retired Lullabies",
      description: "Archive shelf for older lullaby collections.",
      statusLabel: "Archived",
      isPublished: false,
      hasIllustration: true,
      note: "Inactive shelf kept only for historical registry review.",
    },
  ],
};

export const mockupCategoryRegistry: MockupCategorySummary[] = [
  mockupDemoCategory,
  mockupReferenceCategory,
  mockupArchivedCategory,
];

export const mockupStoryPages: MockupStoryPage[] = [
  {
    id: "page-1",
    pageNumber: 1,
    summary: "Arrival at the harbor and first breathing cue.",
    note: "Best page to validate opening-scene illustration density.",
    localizations: [
      {
        languageCode: "en",
        title: "Arrival at the harbor",
        description: "Wide establishing copy with light narration pacing.",
        statusLabel: "Ready",
        isPublished: true,
        hasBodyText: true,
        hasAudio: true,
        hasIllustration: true,
        note: "All localized payloads are present for the English release.",
      },
      {
        languageCode: "tr",
        title: "Limana varis",
        description: "Acilis sayfasi kopyasi ve sakin giris tonu.",
        statusLabel: "Needs audio",
        isPublished: false,
        hasBodyText: true,
        hasAudio: false,
        hasIllustration: true,
        note: "Illustration is approved, but narration is still missing.",
      },
    ],
  },
  {
    id: "page-2",
    pageNumber: 2,
    summary: "Lantern lights and the first story beat.",
    note: "Strong page for testing a long-form editor modal.",
    localizations: [
      {
        languageCode: "en",
        title: "Lantern lights",
        description: "The harbor lights start to slow the scene tempo.",
        statusLabel: "Ready",
        isPublished: true,
        hasBodyText: true,
        hasAudio: true,
        hasIllustration: true,
        note: "Complete payload with polished audio timing.",
      },
      {
        languageCode: "tr",
        title: "Fener isiklari",
        description: "Sahnenin temposunu dusuren ikinci anlatim bolumu.",
        statusLabel: "Needs illustration",
        isPublished: false,
        hasBodyText: true,
        hasAudio: true,
        hasIllustration: false,
        note: "Narration is recorded, but illustration selection is still open.",
      },
    ],
  },
  {
    id: "page-3",
    pageNumber: 3,
    summary: "Boat rhythm and breathing cadence.",
    note: "Useful to preview mixed-ready states inside the table.",
    localizations: [
      {
        languageCode: "en",
        title: "Boat rhythm",
        description: "Mid-story page with rhythmic copy and a longer audio beat.",
        statusLabel: "Ready",
        isPublished: true,
        hasBodyText: true,
        hasAudio: true,
        hasIllustration: true,
        note: "Everything is complete for English.",
      },
      {
        languageCode: "tr",
        title: "Tekne ritmi",
        description: "Nefes temposunu duzenleyen orta bolum.",
        statusLabel: "Needs copy polish",
        isPublished: false,
        hasBodyText: false,
        hasAudio: true,
        hasIllustration: true,
        note: "Asset work is done; editorial copy still needs the final pass.",
      },
    ],
  },
  {
    id: "page-4",
    pageNumber: 4,
    summary: "Final dock scene and the sleep landing.",
    note: "Closing page demonstrates draft completeness and release staging.",
    localizations: [
      {
        languageCode: "en",
        title: "Final dock scene",
        description: "The closing page lands on a short, low-energy cadence.",
        statusLabel: "Ready",
        isPublished: true,
        hasBodyText: true,
        hasAudio: true,
        hasIllustration: true,
        note: "Release-ready closing page.",
      },
      {
        languageCode: "tr",
        title: "Son iskele sahnesi",
        description: "Uykuya gecisi tamamlayan son durak.",
        statusLabel: "Draft",
        isPublished: false,
        hasBodyText: false,
        hasAudio: false,
        hasIllustration: false,
        note: "This page is intentionally sparse to show an early draft state.",
      },
    ],
  },
];
